color0 #3f4943
color1 #ffb4ab
color2 #89d6ae
color3 #afcebb
color4 #bac3ff
color5 #89d6ae
color6 #afcebb
color7 #e0e3de
color8 #89938b
color9 #ffb4ab
color10 #89d6ae
color11 #afcebb
color12 #bac3ff
color13 #89d6ae
color14 #afcebb
color15 #e0e3de

cursor                #e0e3de
cursor_text_color     #000000
background            #000000
foreground            #e0e3de
selection_foreground  #bfc9c1
selection_background  #3f4943
active_border_color   #89d6ae
inactive_border_color #323c36
url_color             #89d6ae

active_tab_foreground   #003824
active_tab_background   #89d6ae
inactive_tab_foreground #bfc9c1
inactive_tab_background #323c36
cursor_trail_color      #bfc9c1
