[keybinds]
'Alt+Tab' = 'window-focus-next'
'Mod+1' = 'workspace-switch:1'
'Mod+2' = 'workspace-switch:2'
'Mod+3' = 'workspace-switch:3'
'Mod+4' = 'workspace-switch:4'
'Mod+5' = 'workspace-switch:5'
'Mod+6' = 'workspace-switch:6'
'Mod+7' = 'workspace-switch:7'
'Mod+8' = 'workspace-switch:8'
'Mod+9' = 'workspace-switch:9'
'Mod+Alt+L' = 'spawn:noctalia msg session lock'
'Mod+Alt+Space' = 'spawn:noctalia msg panel-toggle wallpaper'
'Mod+B' = 'spawn:firefox'
'Mod+C' = 'spawn:alacritty -e agy'
'Mod+Ctrl+K' = 'window-restore-from-scratchpad'
'Mod+D' = 'spawn:noctalia msg panel-toggle launcher'
'Mod+Down' = 'window-focus-down'
'Mod+E' = 'spawn:nautilus'
'Mod+Equal' = 'window-modify-width:0.1'
'Mod+F' = 'window-toggle-fullscreen'
'Mod+H' = 'cheatsheet-toggle'
'Mod+K' = 'scratchpad-toggle'
'Mod+Left' = 'window-focus-left'
'Mod+M' = 'window-toggle-maximize-to-edges'
'Mod+Minus' = 'window-modify-width:-0.1'
'Mod+N' = 'spawn:noctalia msg panel-toggle control-center'
'Mod+O' = 'overview-toggle'
'Mod+P' = 'window-toggle-pinned'
'Mod+Plus' = 'window-modify-width:0.1'
'Mod+Q' = 'window-close'
'Mod+R' = 'spawn:/home/voidlotus/.config/umbriel/scripts/set-layout-ribbon.sh'
'Mod+Return' = 'spawn:alacritty'
'Mod+Right' = 'window-focus-right'
'Mod+S' = 'spawn:noctalia msg settings-toggle'
'Mod+Shift+1' = 'window-move-to-workspace:1'
'Mod+Shift+2' = 'window-move-to-workspace:2'
'Mod+Shift+3' = 'window-move-to-workspace:3'
'Mod+Shift+4' = 'window-move-to-workspace:4'
'Mod+Shift+5' = 'window-move-to-workspace:5'
'Mod+Shift+6' = 'window-move-to-workspace:6'
'Mod+Shift+7' = 'window-move-to-workspace:7'
'Mod+Shift+8' = 'window-move-to-workspace:8'
'Mod+Shift+9' = 'window-move-to-workspace:9'
'Mod+Shift+Down' = 'workspace-next'
'Mod+Shift+F' = 'spawn:/home/voidlotus/.config/umbriel/scripts/toggle-window-floating.sh'
'Mod+Shift+J' = 'spawn:alacritty -e joplin'
'Mod+Shift+K' = 'window-move-to-scratchpad'
'Mod+Shift+P' = 'spawn:/home/voidlotus/.config/umbriel/scripts/toggle-screen-recording.sh'
'Mod+Shift+Q' = 'spawn:noctalia msg panel-toggle session'
'Mod+Shift+Return' = 'spawn:thunar'
'Mod+Shift+S' = 'spawn:noctalia msg panel-toggle control-center'
'Mod+Shift+T' = 'spawn:/home/voidlotus/.config/umbriel/scripts/toggle-workspace-layout.sh'
'Mod+Shift+Up' = 'workspace-previous'
'Mod+Shift+W' = 'spawn:google-chrome-stable'
'Mod+Shift+bracketleft' = 'spawn:/home/voidlotus/.config/hypr/scripts/ScreenShot.sh --area'
'Mod+Space' = 'spawn:/home/voidlotus/.local/bin/ai-overlay'
'Mod+T' = 'spawn:/home/voidlotus/.config/umbriel/scripts/set-layout-dwindle.sh'
'Mod+Tab' = 'scratchpad-focus-next'
'Mod+Up' = 'window-focus-up'
'Mod+V' = 'spawn:noctalia msg panel-toggle launcher'
'Mod+W' = 'spawn:zen-browser'
'Mod+bracketleft' = 'spawn:/home/voidlotus/.config/hypr/scripts/ScreenShot.sh --area'
Print = 'spawn:/home/voidlotus/.config/hypr/scripts/ScreenShot.sh --now'
XF86AudioLowerVolume = 'spawn:noctalia msg volume-down'
XF86AudioMicMute = 'spawn:noctalia msg mic-mute'
XF86AudioMute = 'spawn:noctalia msg volume-mute'
XF86AudioNext = 'spawn:noctalia msg media next'
XF86AudioPause = 'spawn:noctalia msg media toggle'
XF86AudioPlay = 'spawn:noctalia msg media toggle'
XF86AudioPrev = 'spawn:noctalia msg media previous'
XF86AudioRaiseVolume = 'spawn:noctalia msg volume-up'
XF86MonBrightnessDown = 'spawn:noctalia msg brightness-down'
XF86MonBrightnessUp = 'spawn:noctalia msg brightness-up'