# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D2F1DB
background         #1A1E1D
cursor             #80AA90

active_tab_foreground     #1A1E1D
active_tab_background     #D2F1DB
inactive_tab_foreground   #D2F1DB
inactive_tab_background   #1A1E1D

active_border_color   #D2F1DB
inactive_border_color #1A1E1D
bell_border_color     #11211B

color0      #414443
color1		#11211B
color2		#224B34
color3		#2B4C38
color4		#2F6744
color5		#457655
color6		#5FA172
color7		#B7E2C3
color8		#809F88
color9		#162C24
color10		#2E6345
color11		#39654B
color12		#3F8A5B
color13		#5C9E71
color14		#7FD798
color15		#B7E2C3
